# Part generated by configure script
ARCH = x86_64-unknown-linux-gnu
COMMKITPATH = /usr/almagell/ext3/csenning/projects/commkit
INC = -I/usr/almagell/ext3/csenning/projects/commkit
MEXSFX = mexa64
# warning: mex-7.0.1r14sp1 produces binaries that fail unter 7.3
MEX = mex-7.3r2006b CC="/usr/sepp/bin/gcc-4.3.0 -Wall" COPTIMFLAGS="-O2 -DNDEBUG -pipe"
OCTAVE_MEXS_CONDITIONAL = 

# End of auto-configured section

